import { z } from 'zod';
import * as dotenv from 'dotenv';
dotenv.config();

const DEFAULT_PORTS = {
  GATEWAY_HTTP: 4000,
  GATEWAY_HTTPS: 4001,
  BUSINESS_HTTP: 5020,
  BUSINESS_HTTPS: 6020,
  CLUSTER_HTTP: 5014,
  CLUSTER_HTTPS: 6014,
  NOTIFICATION_HTTP: 5006,
  NOTIFICATION_HTTPS: 6006,
  FILE_HTTP: 5007,
  FILE_HTTPS: 6007,
  CRONJOB_HTTP: 5012,
  CRONJOB_HTTPS: 6012,
  KEYCLOAK_API_HTTP: 5013,
  KEYCLOAK_API_HTTPS: 6013,
  REPORT_HTTP: 5015,
  REPORT_HTTPS: 6015,
  REPORT_GRPC: 4015,
  REPORT_RENDER_HTTP: 8001,
  REPORT_RENDER_HTTPS: 8002,
} as const;

// ─── Zod helpers ─────────────────────────────────────────────────────────────

const host = () => z.string().min(1);
const port = (defaultValue: number) => z.coerce.number().default(defaultValue);

// ─── Schema ──────────────────────────────────────────────────────────────────

const envSchema = z.object({
  // JWT
  JWT_SECRET: z.string().min(1, 'JWT_SECRET is required'),
  JWT_EXPIRES_IN: z.string().default('1d'),
  JWT_REFRESH_EXPIRES_IN: z.string().default('7d'),
  JWT_INVITE_EXPIRES_IN: z.string().default('1d'),

  // Gateway
  GATEWAY_SERVICE_HOST: host(),
  GATEWAY_SERVICE_HTTP_PORT: port(DEFAULT_PORTS.GATEWAY_HTTP),
  GATEWAY_SERVICE_HTTPS_PORT: port(DEFAULT_PORTS.GATEWAY_HTTPS),

  // Business (base for consolidated services)
  BUSINESS_SERVICE_HOST: host(),
  BUSINESS_SERVICE_HTTP_PORT: port(DEFAULT_PORTS.BUSINESS_HTTP),
  BUSINESS_SERVICE_HTTPS_PORT: port(DEFAULT_PORTS.BUSINESS_HTTPS),

  // Cluster
  CLUSTER_SERVICE_HOST: host(),
  CLUSTER_SERVICE_HTTP_PORT: port(DEFAULT_PORTS.CLUSTER_HTTP),
  CLUSTER_SERVICE_HTTPS_PORT: port(DEFAULT_PORTS.CLUSTER_HTTPS),

  // Notification
  NOTIFICATION_SERVICE_HOST: host(),
  NOTIFICATION_SERVICE_HTTP_PORT: port(DEFAULT_PORTS.NOTIFICATION_HTTP),
  NOTIFICATION_SERVICE_HTTPS_PORT: port(DEFAULT_PORTS.NOTIFICATION_HTTPS),

  // File
  FILE_SERVICE_HOST: host(),
  FILE_SERVICE_HTTP_PORT: port(DEFAULT_PORTS.FILE_HTTP),
  FILE_SERVICE_HTTPS_PORT: port(DEFAULT_PORTS.FILE_HTTPS),

  // Cronjob
  CRONJOB_SERVICE_HOST: host(),
  CRONJOB_SERVICE_HTTP_PORT: port(DEFAULT_PORTS.CRONJOB_HTTP),
  CRONJOB_SERVICE_HTTPS_PORT: port(DEFAULT_PORTS.CRONJOB_HTTPS),

  // Keycloak API
  KEYCLOAK_API_SERVICE_HOST: host(),
  KEYCLOAK_API_SERVICE_HTTP_PORT: port(DEFAULT_PORTS.KEYCLOAK_API_HTTP),
  KEYCLOAK_API_SERVICE_HTTPS_PORT: port(DEFAULT_PORTS.KEYCLOAK_API_HTTPS),

  // Report
  REPORT_SERVICE_HOST: host(),
  REPORT_SERVICE_HTTP_PORT: port(DEFAULT_PORTS.REPORT_HTTP),
  REPORT_SERVICE_HTTPS_PORT: port(DEFAULT_PORTS.REPORT_HTTPS),
  REPORT_SERVICE_GRPC_PORT: port(DEFAULT_PORTS.REPORT_GRPC),

  // Report Render
  REPORT_RENDER_HOST: host(),
  REPORT_RENDER_HTTP_PORT: port(DEFAULT_PORTS.REPORT_RENDER_HTTP),
  REPORT_RENDER_HTTPS_PORT: port(DEFAULT_PORTS.REPORT_RENDER_HTTPS),

  // Database
  SYSTEM_DATABASE_URL: z.string().min(1, 'SYSTEM_DATABASE_URL is required'),
  SYSTEM_DIRECT_URL: z.string().min(1, 'SYSTEM_DIRECT_URL is required'),

  // User invitation/registration
  INVITATION_LIMIT_HOURS: z.coerce.number().default(24),
  REGISTER_BASE_URL: z.string().default('http://localhost:3000'),
  RESET_PASSWORD_LIMIT_HOURS: z.coerce.number().default(24),
  RESET_PASSWORD_BASE_URL: z.string().default('http://localhost:3000'),

  // SMTP
  SMTP_HOST: z.string().default('smtp.example.com'),
  SMTP_PORT: z.coerce.number().default(587),
  SMTP_USER: z.string().default(''),
  SMTP_PASS: z.string().default(''),
  SMTP_FROM: z.string().default('noreply@example.com'),

  // Sentry
  SENTRY_DSN: z.string().optional(),
});

// ─── Parse & validate ────────────────────────────────────────────────────────

const parsed = envSchema.safeParse(process.env);

if (!parsed.success) {
  const missing = parsed.error.issues.map(
    (i) => `  - ${i.path.join('.')}: ${i.message}`,
  );
  console.error(
    `\n❌ Missing/invalid environment variables:\n${missing.join('\n')}\n`,
  );
  process.exit(1);
}

const env = parsed.data;

// ─── Export ──────────────────────────────────────────────────────────────────

export const envConfig = {
  // Gateway
  GATEWAY_SERVICE_HOST: env.GATEWAY_SERVICE_HOST,
  GATEWAY_SERVICE_HTTP_PORT: env.GATEWAY_SERVICE_HTTP_PORT,
  GATEWAY_SERVICE_HTTPS_PORT: env.GATEWAY_SERVICE_HTTPS_PORT,

  // Business (consolidated: auth, master, inventory, procurement, log)
  BUSINESS_SERVICE_HOST: env.BUSINESS_SERVICE_HOST,
  BUSINESS_SERVICE_HTTP_PORT: env.BUSINESS_SERVICE_HTTP_PORT,
  BUSINESS_SERVICE_HTTPS_PORT: env.BUSINESS_SERVICE_HTTPS_PORT,

  // Cluster
  CLUSTER_SERVICE_HOST: env.CLUSTER_SERVICE_HOST,
  CLUSTER_SERVICE_HTTP_PORT: env.CLUSTER_SERVICE_HTTP_PORT,
  CLUSTER_SERVICE_HTTPS_PORT: env.CLUSTER_SERVICE_HTTPS_PORT,

  // Notification
  NOTIFICATION_SERVICE_HOST: env.NOTIFICATION_SERVICE_HOST,
  NOTIFICATION_SERVICE_HTTP_PORT: env.NOTIFICATION_SERVICE_HTTP_PORT,
  NOTIFICATION_SERVICE_HTTPS_PORT: env.NOTIFICATION_SERVICE_HTTPS_PORT,

  // File
  FILE_SERVICE_HOST: env.FILE_SERVICE_HOST,
  FILE_SERVICE_HTTP_PORT: env.FILE_SERVICE_HTTP_PORT,
  FILE_SERVICE_HTTPS_PORT: env.FILE_SERVICE_HTTPS_PORT,

  // Cronjob
  CRONJOB_SERVICE_HOST: env.CRONJOB_SERVICE_HOST,
  CRONJOB_SERVICE_HTTP_PORT: env.CRONJOB_SERVICE_HTTP_PORT,
  CRONJOB_SERVICE_HTTPS_PORT: env.CRONJOB_SERVICE_HTTPS_PORT,

  // Keycloak API
  KEYCLOAK_API_SERVICE_HOST: env.KEYCLOAK_API_SERVICE_HOST,
  KEYCLOAK_API_SERVICE_HTTP_PORT: env.KEYCLOAK_API_SERVICE_HTTP_PORT,
  KEYCLOAK_API_SERVICE_HTTPS_PORT: env.KEYCLOAK_API_SERVICE_HTTPS_PORT,

  // Report
  REPORT_SERVICE_HOST: env.REPORT_SERVICE_HOST,
  REPORT_SERVICE_HTTP_PORT: env.REPORT_SERVICE_HTTP_PORT,
  REPORT_SERVICE_HTTPS_PORT: env.REPORT_SERVICE_HTTPS_PORT,
  REPORT_SERVICE_GRPC_PORT: env.REPORT_SERVICE_GRPC_PORT,

  // Report Render
  REPORT_RENDER_HOST: env.REPORT_RENDER_HOST,
  REPORT_RENDER_HTTP_PORT: env.REPORT_RENDER_HTTP_PORT,
  REPORT_RENDER_HTTPS_PORT: env.REPORT_RENDER_HTTPS_PORT,

  // Database
  SYSTEM_DATABASE_URL: env.SYSTEM_DATABASE_URL,
  SYSTEM_DIRECT_URL: env.SYSTEM_DIRECT_URL,

  // JWT
  JWT_SECRET: env.JWT_SECRET,
  JWT_EXPIRES_IN: env.JWT_EXPIRES_IN,
  JWT_REFRESH_EXPIRES_IN: env.JWT_REFRESH_EXPIRES_IN,
  JWT_INVITE_EXPIRES_IN: env.JWT_INVITE_EXPIRES_IN,

  // User invitation/registration
  INVITATION_LIMIT_HOURS: env.INVITATION_LIMIT_HOURS,
  REGISTER_BASE_URL: env.REGISTER_BASE_URL,
  RESET_PASSWORD_LIMIT_HOURS: env.RESET_PASSWORD_LIMIT_HOURS,
  RESET_PASSWORD_BASE_URL: env.RESET_PASSWORD_BASE_URL,

  // SMTP
  SMTP_HOST: env.SMTP_HOST,
  SMTP_PORT: env.SMTP_PORT,
  SMTP_USER: env.SMTP_USER,
  SMTP_PASS: env.SMTP_PASS,
  SMTP_FROM: env.SMTP_FROM,

  // Sentry
  SENTRY_DSN: env.SENTRY_DSN,
};
