import { z } from 'zod';
import * as dotenv from 'dotenv';
dotenv.config();

const DEFAULT_HOST = 'localhost';
const DEFAULT_PORTS = {
  GATEWAY: 4000,
  GATEWAY_HTTPS: 4001,
  // micro-business consolidated service (auth, log, inventory, master, procurement, recipe)
  BUSINESS: 5020,
  AUTH: 5020,
  // micro-cluster service (separated from micro-business)
  CLUSTER: 5014,
  LICENSE: 5014,
  TENANT_INVENTORY: 5020,
  TENANT_PROCUREMENT: 5020,
  TENANT_RECIPE: 5020,
  TENANT_MASTER: 5020,
  LOG: 5020,
  // Separate services
  REPORT: 5004,
  NOTIFICATION: 5006,
  FILE: 5007,
  CRONJOB: 5012,
  KEYCLOAK_API: 5013,
};

const envSchema = z.object({
  // Required
  SUPABASE_JWT_SECRET: z.string().min(1, 'SUPABASE_JWT_SECRET is required'),

  // Gateway service
  GATEWAY_SERVICE_HOST: z.string().default(DEFAULT_HOST),
  GATEWAY_SERVICE_PORT: z.coerce.number().default(DEFAULT_PORTS.GATEWAY),
  GATEWAY_SERVICE_HTTPS_PORT: z.coerce
    .number()
    .default(DEFAULT_PORTS.GATEWAY_HTTPS),

  // Business service (base for consolidated services)
  BUSINESS_SERVICE_HOST: z.string().default(DEFAULT_HOST),
  BUSINESS_SERVICE_PORT: z.coerce.number().default(DEFAULT_PORTS.BUSINESS),
  BUSINESS_SERVICE_HTTP_PORT: z.coerce.number().default(6020),

  // Consolidated services (fallback to BUSINESS_SERVICE_*)
  AUTH_SERVICE_HOST: z.string().optional(),
  AUTH_SERVICE_PORT: z.coerce.number().optional(),
  AUTH_SERVICE_HTTP_PORT: z.coerce.number().optional(),

  CLUSTER_SERVICE_HOST: z.string().default(DEFAULT_HOST),
  CLUSTER_SERVICE_PORT: z.coerce.number().default(DEFAULT_PORTS.CLUSTER),
  CLUSTER_SERVICE_HTTP_PORT: z.coerce.number().default(6014),

  LICENSE_SERVICE_HOST: z.string().optional(),
  LICENSE_SERVICE_PORT: z.coerce.number().optional(),
  LICENSE_SERVICE_HTTP_PORT: z.coerce.number().optional(),

  INVENTORY_SERVICE_HOST: z.string().optional(),
  INVENTORY_SERVICE_PORT: z.coerce.number().optional(),
  INVENTORY_SERVICE_HTTP_PORT: z.coerce.number().optional(),

  PROCUREMENT_SERVICE_HOST: z.string().optional(),
  PROCUREMENT_SERVICE_PORT: z.coerce.number().optional(),
  PROCUREMENT_SERVICE_HTTP_PORT: z.coerce.number().optional(),

  RECIPE_SERVICE_HOST: z.string().optional(),
  RECIPE_SERVICE_PORT: z.coerce.number().optional(),
  RECIPE_SERVICE_HTTP_PORT: z.coerce.number().optional(),

  MASTER_SERVICE_HOST: z.string().optional(),
  MASTER_SERVICE_PORT: z.coerce.number().optional(),
  MASTER_SERVICE_HTTP_PORT: z.coerce.number().optional(),

  LOG_SERVICE_HOST: z.string().optional(),
  LOG_SERVICE_PORT: z.coerce.number().optional(),
  LOG_SERVICE_HTTP_PORT: z.coerce.number().optional(),

  // Standalone services
  REPORT_SERVICE_HOST: z.string().default(DEFAULT_HOST),
  REPORT_SERVICE_PORT: z.coerce.number().default(DEFAULT_PORTS.REPORT),
  REPORT_SERVICE_HTTP_PORT: z.coerce.number().default(6004),

  NOTIFICATION_SERVICE_HOST: z.string().default(DEFAULT_HOST),
  NOTIFICATION_SERVICE_PORT: z.coerce
    .number()
    .default(DEFAULT_PORTS.NOTIFICATION),
  NOTIFICATION_SERVICE_HTTP_PORT: z.coerce.number().default(6006),

  FILE_SERVICE_HOST: z.string().default(DEFAULT_HOST),
  FILE_SERVICE_PORT: z.coerce.number().default(DEFAULT_PORTS.FILE),
  FILE_SERVICE_HTTP_PORT: z.coerce.number().default(6007),

  CRONJOB_SERVICE_HOST: z.string().default(DEFAULT_HOST),
  CRONJOB_SERVICE_PORT: z.coerce.number().default(DEFAULT_PORTS.CRONJOB),
  CRONJOB_SERVICE_HTTP_PORT: z.coerce.number().default(6012),

  KEYCLOAK_API_SERVICE_HOST: z.string().default(DEFAULT_HOST),
  KEYCLOAK_API_SERVICE_PORT: z.coerce
    .number()
    .default(DEFAULT_PORTS.KEYCLOAK_API),

  IS_ACTIVE_NOTIFICATION: z.string().optional(),
});

const parsed = envSchema.safeParse(process.env);

if (!parsed.success) {
  const missing = parsed.error.issues.map(
    (i) => `  - ${i.path.join('.')}: ${i.message}`,
  );
  console.error(
    `\n❌ Missing/invalid environment variables:\n${missing.join('\n')}\n`,
  );
  process.exit(1);
}

const env = parsed.data;

export const envConfig = {
  GATEWAY_SERVICE_HOST: env.GATEWAY_SERVICE_HOST,
  GATEWAY_SERVICE_PORT: env.GATEWAY_SERVICE_PORT,
  GATEWAY_SERVICE_HTTPS_PORT: env.GATEWAY_SERVICE_HTTPS_PORT,

  // micro-business consolidated service
  BUSINESS_SERVICE_HOST: env.BUSINESS_SERVICE_HOST,
  BUSINESS_SERVICE_PORT: env.BUSINESS_SERVICE_PORT,
  BUSINESS_SERVICE_HTTP_PORT: env.BUSINESS_SERVICE_HTTP_PORT,

  // Legacy aliases - all fallback to BUSINESS_SERVICE_*
  AUTH_SERVICE_HOST:
    env.AUTH_SERVICE_HOST ?? env.BUSINESS_SERVICE_HOST,
  AUTH_SERVICE_PORT:
    env.AUTH_SERVICE_PORT ?? env.BUSINESS_SERVICE_PORT,
  AUTH_SERVICE_HTTP_PORT:
    env.AUTH_SERVICE_HTTP_PORT ?? env.BUSINESS_SERVICE_HTTP_PORT,

  CLUSTER_SERVICE_HOST: env.CLUSTER_SERVICE_HOST,
  CLUSTER_SERVICE_PORT: env.CLUSTER_SERVICE_PORT,
  CLUSTER_SERVICE_HTTP_PORT: env.CLUSTER_SERVICE_HTTP_PORT,

  LICENSE_SERVICE_HOST:
    env.LICENSE_SERVICE_HOST ?? env.CLUSTER_SERVICE_HOST,
  LICENSE_SERVICE_PORT:
    env.LICENSE_SERVICE_PORT ?? env.CLUSTER_SERVICE_PORT,
  LICENSE_SERVICE_HTTP_PORT:
    env.LICENSE_SERVICE_HTTP_PORT ?? env.CLUSTER_SERVICE_HTTP_PORT,

  REPORT_SERVICE_HOST: env.REPORT_SERVICE_HOST,
  REPORT_SERVICE_PORT: env.REPORT_SERVICE_PORT,
  REPORT_SERVICE_HTTP_PORT: env.REPORT_SERVICE_HTTP_PORT,

  NOTIFICATION_SERVICE_HOST: env.NOTIFICATION_SERVICE_HOST,
  NOTIFICATION_SERVICE_PORT: env.NOTIFICATION_SERVICE_PORT,
  NOTIFICATION_SERVICE_HTTP_PORT: env.NOTIFICATION_SERVICE_HTTP_PORT,

  FILE_SERVICE_HOST: env.FILE_SERVICE_HOST,
  FILE_SERVICE_PORT: env.FILE_SERVICE_PORT,
  FILE_SERVICE_HTTP_PORT: env.FILE_SERVICE_HTTP_PORT,

  INVENTORY_SERVICE_HOST:
    env.INVENTORY_SERVICE_HOST ?? env.BUSINESS_SERVICE_HOST,
  INVENTORY_SERVICE_PORT:
    env.INVENTORY_SERVICE_PORT ?? env.BUSINESS_SERVICE_PORT,
  INVENTORY_SERVICE_HTTP_PORT:
    env.INVENTORY_SERVICE_HTTP_PORT ?? env.BUSINESS_SERVICE_HTTP_PORT,

  PROCUREMENT_SERVICE_HOST:
    env.PROCUREMENT_SERVICE_HOST ?? env.BUSINESS_SERVICE_HOST,
  PROCUREMENT_SERVICE_PORT:
    env.PROCUREMENT_SERVICE_PORT ?? env.BUSINESS_SERVICE_PORT,
  PROCUREMENT_SERVICE_HTTP_PORT:
    env.PROCUREMENT_SERVICE_HTTP_PORT ?? env.BUSINESS_SERVICE_HTTP_PORT,

  RECIPE_SERVICE_HOST:
    env.RECIPE_SERVICE_HOST ?? env.BUSINESS_SERVICE_HOST,
  RECIPE_SERVICE_PORT:
    env.RECIPE_SERVICE_PORT ?? env.BUSINESS_SERVICE_PORT,
  RECIPE_SERVICE_HTTP_PORT:
    env.RECIPE_SERVICE_HTTP_PORT ?? env.BUSINESS_SERVICE_HTTP_PORT,

  MASTER_SERVICE_HOST:
    env.MASTER_SERVICE_HOST ?? env.BUSINESS_SERVICE_HOST,
  MASTER_SERVICE_PORT:
    env.MASTER_SERVICE_PORT ?? env.BUSINESS_SERVICE_PORT,
  MASTER_SERVICE_HTTP_PORT:
    env.MASTER_SERVICE_HTTP_PORT ?? env.BUSINESS_SERVICE_HTTP_PORT,

  CRONJOB_SERVICE_HOST: env.CRONJOB_SERVICE_HOST,
  CRONJOB_SERVICE_PORT: env.CRONJOB_SERVICE_PORT,
  CRONJOB_SERVICE_HTTP_PORT: env.CRONJOB_SERVICE_HTTP_PORT,

  KEYCLOAK_API_SERVICE_HOST: env.KEYCLOAK_API_SERVICE_HOST,
  KEYCLOAK_API_SERVICE_PORT: env.KEYCLOAK_API_SERVICE_PORT,

  LOG_SERVICE_HOST:
    env.LOG_SERVICE_HOST ?? env.BUSINESS_SERVICE_HOST,
  LOG_SERVICE_PORT:
    env.LOG_SERVICE_PORT ?? env.BUSINESS_SERVICE_PORT,
  LOG_SERVICE_HTTP_PORT:
    env.LOG_SERVICE_HTTP_PORT ?? env.BUSINESS_SERVICE_HTTP_PORT,

  IS_ACTIVE_NOTIFICATION: Boolean(env.IS_ACTIVE_NOTIFICATION),

  SUPABASE_JWT_SECRET: env.SUPABASE_JWT_SECRET,
};
