import { z } from 'zod';
import * as dotenv from 'dotenv';
dotenv.config();

const DEFAULT_PORTS = {
  GATEWAY_HTTP: 4000,
  GATEWAY_HTTPS: 4001,
  BUSINESS_TCP: 5020,
  BUSINESS_HTTP: 6020,
  CLUSTER_TCP: 5014,
  CLUSTER_HTTP: 6014,
  NOTIFICATION_TCP: 5006,
  NOTIFICATION_HTTP: 6006,
  FILE_TCP: 5007,
  FILE_HTTP: 6007,
  CRONJOB_TCP: 5012,
  CRONJOB_HTTP: 6012,
  KEYCLOAK_API_TCP: 5013,
  KEYCLOAK_API_HTTP: 6013,
  REPORT_TCP: 5015,
  REPORT_HTTP: 6015,
  REPORT_GRPC: 4015,
  REPORT_RENDER_TCP: 8001,
  REPORT_RENDER_HTTP: 8002,
} as const;

// ─── Zod helpers ─────────────────────────────────────────────────────────────

const host = () => z.string().min(1);
const port = (defaultValue: number) => z.coerce.number().default(defaultValue);

// ─── Schema ──────────────────────────────────────────────────────────────────

const envSchema = z.object({
  // Gateway
  GATEWAY_SERVICE_HOST: host(),
  GATEWAY_SERVICE_HTTP_PORT: port(DEFAULT_PORTS.GATEWAY_HTTP),
  GATEWAY_SERVICE_HTTPS_PORT: port(DEFAULT_PORTS.GATEWAY_HTTPS),

  // Business
  BUSINESS_SERVICE_HOST: host(),
  BUSINESS_SERVICE_TCP_PORT: port(DEFAULT_PORTS.BUSINESS_TCP),
  BUSINESS_SERVICE_HTTP_PORT: port(DEFAULT_PORTS.BUSINESS_HTTP),

  // Cluster
  CLUSTER_SERVICE_HOST: host(),
  CLUSTER_SERVICE_TCP_PORT: port(DEFAULT_PORTS.CLUSTER_TCP),
  CLUSTER_SERVICE_HTTP_PORT: port(DEFAULT_PORTS.CLUSTER_HTTP),

  // Notification
  NOTIFICATION_SERVICE_HOST: host(),
  NOTIFICATION_SERVICE_TCP_PORT: port(DEFAULT_PORTS.NOTIFICATION_TCP),
  NOTIFICATION_SERVICE_HTTP_PORT: port(DEFAULT_PORTS.NOTIFICATION_HTTP),

  // File
  FILE_SERVICE_HOST: host(),
  FILE_SERVICE_TCP_PORT: port(DEFAULT_PORTS.FILE_TCP),
  FILE_SERVICE_HTTP_PORT: port(DEFAULT_PORTS.FILE_HTTP),

  // Cronjob
  CRONJOB_SERVICE_HOST: host(),
  CRONJOB_SERVICE_TCP_PORT: port(DEFAULT_PORTS.CRONJOB_TCP),
  CRONJOB_SERVICE_HTTP_PORT: port(DEFAULT_PORTS.CRONJOB_HTTP),

  // Keycloak API
  KEYCLOAK_API_SERVICE_HOST: host(),
  KEYCLOAK_API_SERVICE_TCP_PORT: port(DEFAULT_PORTS.KEYCLOAK_API_TCP),
  KEYCLOAK_API_SERVICE_HTTP_PORT: port(DEFAULT_PORTS.KEYCLOAK_API_HTTP),

  // Report
  REPORT_SERVICE_HOST: host(),
  REPORT_SERVICE_TCP_PORT: port(DEFAULT_PORTS.REPORT_TCP),
  REPORT_SERVICE_HTTP_PORT: port(DEFAULT_PORTS.REPORT_HTTP),
  REPORT_SERVICE_GRPC_PORT: port(DEFAULT_PORTS.REPORT_GRPC),

  // Report Render
  REPORT_RENDER_HOST: host(),
  REPORT_RENDER_TCP_PORT: port(DEFAULT_PORTS.REPORT_RENDER_TCP),
  REPORT_RENDER_HTTP_PORT: port(DEFAULT_PORTS.REPORT_RENDER_HTTP),

  // Database
  SYSTEM_DATABASE_URL: z.string().min(1, 'SYSTEM_DATABASE_URL is required'),
  SYSTEM_DIRECT_URL: z.string().min(1, 'SYSTEM_DIRECT_URL is required'),

  // User invitation/registration
  INVITATION_LIMIT_HOURS: z.coerce.number().default(24),
  REGISTER_BASE_URL: z.string().default('http://localhost:3000'),
  RESET_PASSWORD_LIMIT_HOURS: z.coerce.number().default(24),
  RESET_PASSWORD_BASE_URL: z.string().default('http://localhost:3000'),

  // SMTP
  SMTP_HOST: z.string().default('smtp.example.com'),
  SMTP_PORT: z.coerce.number().default(587),
  SMTP_USER: z.string().default(''),
  SMTP_PASS: z.string().default(''),
  SMTP_FROM: z.string().default('noreply@example.com'),

  // Logging
  LOG_LEVEL: z.string().default('info'),

  // Sentry
  SENTRY_DSN: z.string().optional(),
});

// ─── Parse & validate ────────────────────────────────────────────────────────

const parsed = envSchema.safeParse(process.env);

if (!parsed.success) {
  const missing = parsed.error.issues.map(
    (i) => `  - ${i.path.join('.')}: ${i.message}`,
  );
  console.error(
    `\n❌ Missing/invalid environment variables:\n${missing.join('\n')}\n`,
  );
  process.exit(1);
}

const env = parsed.data;

// ─── Export ──────────────────────────────────────────────────────────────────

export const envConfig = {
  // Gateway
  GATEWAY_SERVICE_HOST: env.GATEWAY_SERVICE_HOST,
  GATEWAY_SERVICE_HTTP_PORT: env.GATEWAY_SERVICE_HTTP_PORT,
  GATEWAY_SERVICE_HTTPS_PORT: env.GATEWAY_SERVICE_HTTPS_PORT,

  // Business
  BUSINESS_SERVICE_HOST: env.BUSINESS_SERVICE_HOST,
  BUSINESS_SERVICE_TCP_PORT: env.BUSINESS_SERVICE_TCP_PORT,
  BUSINESS_SERVICE_HTTP_PORT: env.BUSINESS_SERVICE_HTTP_PORT,

  // Cluster
  CLUSTER_SERVICE_HOST: env.CLUSTER_SERVICE_HOST,
  CLUSTER_SERVICE_TCP_PORT: env.CLUSTER_SERVICE_TCP_PORT,
  CLUSTER_SERVICE_HTTP_PORT: env.CLUSTER_SERVICE_HTTP_PORT,

  // Notification
  NOTIFICATION_SERVICE_HOST: env.NOTIFICATION_SERVICE_HOST,
  NOTIFICATION_SERVICE_TCP_PORT: env.NOTIFICATION_SERVICE_TCP_PORT,
  NOTIFICATION_SERVICE_HTTP_PORT: env.NOTIFICATION_SERVICE_HTTP_PORT,

  // File
  FILE_SERVICE_HOST: env.FILE_SERVICE_HOST,
  FILE_SERVICE_TCP_PORT: env.FILE_SERVICE_TCP_PORT,
  FILE_SERVICE_HTTP_PORT: env.FILE_SERVICE_HTTP_PORT,

  // Cronjob
  CRONJOB_SERVICE_HOST: env.CRONJOB_SERVICE_HOST,
  CRONJOB_SERVICE_TCP_PORT: env.CRONJOB_SERVICE_TCP_PORT,
  CRONJOB_SERVICE_HTTP_PORT: env.CRONJOB_SERVICE_HTTP_PORT,

  // Keycloak API
  KEYCLOAK_API_SERVICE_HOST: env.KEYCLOAK_API_SERVICE_HOST,
  KEYCLOAK_API_SERVICE_TCP_PORT: env.KEYCLOAK_API_SERVICE_TCP_PORT,
  KEYCLOAK_API_SERVICE_HTTP_PORT: env.KEYCLOAK_API_SERVICE_HTTP_PORT,

  // Report
  REPORT_SERVICE_HOST: env.REPORT_SERVICE_HOST,
  REPORT_SERVICE_TCP_PORT: env.REPORT_SERVICE_TCP_PORT,
  REPORT_SERVICE_HTTP_PORT: env.REPORT_SERVICE_HTTP_PORT,
  REPORT_SERVICE_GRPC_PORT: env.REPORT_SERVICE_GRPC_PORT,

  // Report Render
  REPORT_RENDER_HOST: env.REPORT_RENDER_HOST,
  REPORT_RENDER_TCP_PORT: env.REPORT_RENDER_TCP_PORT,
  REPORT_RENDER_HTTP_PORT: env.REPORT_RENDER_HTTP_PORT,

  // Database
  SYSTEM_DATABASE_URL: env.SYSTEM_DATABASE_URL,
  SYSTEM_DIRECT_URL: env.SYSTEM_DIRECT_URL,

  // User invitation/registration
  INVITATION_LIMIT_HOURS: env.INVITATION_LIMIT_HOURS,
  REGISTER_BASE_URL: env.REGISTER_BASE_URL,
  RESET_PASSWORD_LIMIT_HOURS: env.RESET_PASSWORD_LIMIT_HOURS,
  RESET_PASSWORD_BASE_URL: env.RESET_PASSWORD_BASE_URL,

  // SMTP
  SMTP_HOST: env.SMTP_HOST,
  SMTP_PORT: env.SMTP_PORT,
  SMTP_USER: env.SMTP_USER,
  SMTP_PASS: env.SMTP_PASS,
  SMTP_FROM: env.SMTP_FROM,

  // Logging
  LOG_LEVEL: env.LOG_LEVEL,

  // Sentry
  SENTRY_DSN: env.SENTRY_DSN,
};
